Logging with multiprocessing
brian-team/brian2 pull request #1419
Opened 2022-05-11 12:04 UTC by mstimberg

See the discussion in #1418. This PR changes the default file log level to DEBUG, switches off file logging when the logger is accessed from a process different from the one that called `BrianLogger.initialize()`, and updated the documentation accordingly.

@schmitts & @thesamovar, let me know if anything is unclear or could be improved.

Fixes #1418

2022-05-13 08:54 UTC, mstimberg commented
There were a few issues with running the multiprocessing tests under OS X and Windows (of course there were), but now all tests pass on all platforms.

2022-06-08 13:11 UTC, mstimberg commented
Hi @bdevans, @thesamovar any comments on the PR? I think it is rather safe to merge in the sense that it should clearly improve things, but if you could have a quick look I'd be grateful. I'd prefer to rather merge it soon, so I propose to turn this into a "merge unless someone objects" instead of waiting for a positive review :blush:

2022-06-08 14:48 UTC, thesamovar commented
Have you tried running actual examples (not tests) in Windows? I feel like with multiprocessing stuff that's important because there are all sorts of weirdnesses and I don't know how well the test suite reproduces that?

2022-06-08 15:57 UTC, mstimberg commented
I did run the [multiprocessing examples](https://brian2.readthedocs.io/en/stable/examples/index.html#multiprocessing) and [Graupner & Brunel (2012)](https://brian2.readthedocs.io/en/latest/examples/frompapers.Graupner_Brunel_2012.html). They ran successfully – I did not verify in detail whether it actually switches off the log, though. I guess if the corresponding test passes, there is no reason this should not work?
The [Maass et al. (2002)](https://brian2.readthedocs.io/en/latest/examples/frompapers.Maass_Natschlaeger_Markram_2002.html) example also uses multiprocessing, but I recently realized it does not work under Windows (a function should be declared on the module level instead of in the `__main__` block, I think). But it does not work in `master`, either, so this problem is unrelated to this PR.

2022-06-09 13:47 UTC, bdevans requested changes
A few minor tweaks to make but otherwise looks fine. I might lean towards generating a separate log file for each process, calling them something like `f"{log_file_basename}_{pid}.log"` but that might generate too much output so having just one log file for the master process is fine.

2022-06-09 13:47 UTC, bdevans commented on docs_sphinx/advanced/logging.rst
> +Brian's logging system is not designed for multiple parrallel Brian processes
Typo in parallel

2022-06-09 13:47 UTC, bdevans commented on dev/continuous-integration/run_test_suite.py
> +                             test_GSL=True,
There's a cheeky extra space here!

2022-06-09 13:47 UTC, bdevans commented on dev/continuous-integration/run_test_suite.py
> +                             test_GSL=True,
There's a cheeky extra space here!

2022-06-09 13:47 UTC, bdevans commented on docs_sphinx/advanced/logging.rst
> +therefore consider to use e.g. `BrianLogger.log_level_error()` to only show error
"wish to use" or "consider using" would be slightly more natural here.

2022-06-09 13:47 UTC, bdevans commented on docs_sphinx/advanced/logging.rst
> +therefore consider to use e.g. `BrianLogger.log_level_error()` to only show error
"wish to use" or "consider using" would be slightly more natural here.

2022-06-09 14:31 UTC, mstimberg commented
Thanks @bdevans for the review, I think the issues should be fixed now.

> I might lean towards generating a separate log file for each process, calling them something like `f"{log_file_basename}_{pid}.log"` but that might generate too much output so having just one log file for the master process is fine.

Yes, I agree that this would make sense as well. On the other hand, the logged information in the subprocesses will most likely be very similar (if not identical), and if you launch many of them, this could become annoying. IMO, the vast majority of users do not care about the log, and for those who do, the manual method gives them a way to have individual logs per subprocess.

2022-06-09 16:34 UTC, bdevans commented
Thanks Marcel, it looks good to me now but for some reason I can't approve the changes (I can only seem to dismiss or re-request the review) - any ideas what's gone wrong?

2022-06-09 16:48 UTC, thesamovar commented
> I did run the [multiprocessing examples](https://brian2.readthedocs.io/en/stable/examples/index.html#multiprocessing) and [Graupner & Brunel (2012)](https://brian2.readthedocs.io/en/latest/examples/frompapers.Graupner_Brunel_2012.html). They ran successfully – I did not verify in detail whether it actually switches off the log, though. I guess if the corresponding test passes, there is no reason this should not work? The [Maass et al. (2002)](https://brian2.readthedocs.io/en/latest/examples/frompapers.Maass_Natschlaeger_Markram_2002.html) example also uses multiprocessing, but I recently realized it does not work under Windows (a function should be declared on the module level instead of in the `__main__` block, I think). But it does not work in `master`, either, so this problem is unrelated to this PR.

As long as it's not breaking I guess it's OK! If Ben is happy with the code I'm happy too.

2022-06-09 17:53 UTC, bdevans approved these changes

2022-06-09 17:58 UTC, merged